server:
  port: 9000

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: output-service
          uri: ${OUTPUT_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/output/**
        - id: scan-service
          uri: ${SCAN_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/api/scan/**
        - id: user-service
          uri: ${USER_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/api/user/**

  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/network-scanner
          jwk-set-uri: ${KEYCLOAK_URI:http://localhost:8181/realms/network-scanner/protocol/openid-connect/certs}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG


