server:
  ssl:
    key-store: src/main/resources/springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8443

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/network-scanner
logging:
  level:
    org.springframework.cloud.gateway: DEBUG