server:
  port: 9000

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: output-service
          uri: http://output-service:8081
          predicates:
            - Path=/api/output/**
        - id: scan-service
          uri: http://scan-service:8080
          predicates:
            - Path=/api/scan/**
        - id: user-service
          uri: http://userservice:8083
          predicates:
            - Path=/api/user/**

  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/network-scanner
          jwk-set-uri: http://keycloak:8080/realms/network-scanner/protocol/openid-connect/certs
logging:
  level:
    org.springframework.cloud.gateway: DEBUG


