server:
  port: 9000

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: output-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/output/**
        - id: scan-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/scan/**
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/user/**

  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/network-scanner
logging:
  level:
    org.springframework.cloud.gateway: DEBUG


