services:
  mongodb:
    image: mongo:7.0.5
    container_name: scan-processing-output-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: web-scan-app
    volumes:
      - ./data:/data/db